[project]
name = "trie-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.27.2",
    "lxml>=5.3.0",
    "pytest>=8.3.3",
    "rich>=13.9.4",
    "ruff>=0.6.9",
]
